Split `Event::Text` into `Text` and `Paste`
emilk/egui pull request #1058
Opened 2022-01-09 02:46 UTC by psiphi75

As lightly discussed on Discord.  Here is the draft PR for separating a `Paste` event and `Text` input event. The purpose is such that we can paste text into the window, without needing to be in a text box, and then we know that it's paste event, and not just keyboard input.

Note: This will likely break some applications which rely on the `Text` input event for a paste.

Closes <https://github.com/emilk/egui/issues/1057>.

2022-01-09 14:27 UTC, emilk commented
Looks good! Please add it to the main CHANGELOG.md

2022-01-10 09:00 UTC, psiphi75 commented
Thanks.  I've updated the main CHANGELOG.md.

2022-01-10 21:23 UTC, emilk requested changes

2022-01-10 21:23 UTC, emilk commented on CHANGELOG.md
> +* Split `Event::Text` into `Event::Text` and `Event::Paste` ([#1057](https://github.com/emilk/egui/issues/1057).
```suggestion
* Split `Event::Text` into `Event::Text` and `Event::Paste` ([#1058](https://github.com/emilk/egui/pull/1058)).
```

2022-01-10 21:23 UTC, emilk approved these changes

2022-01-10 22:12 UTC, merged