Draft: Add ability to convert from a hex string to Color32 using macros
emilk/egui pull request #1596
Opened 2022-05-07 05:22 UTC by newcomb-luke

This PR closes <https://github.com/emilk/egui/issues/1492>.

Again currently `./sh/check.sh` is currently failing for me, see my other [PR](https://github.com/emilk/egui/pull/1595).
Cargo clippy and cargo fmt have both been run.
The CHANGELOG.md has been updated under "Unreleased"

This change allows you to create Color32's from hex strings:

```rust
let color = epaint::hex_rgb!("#4c4c4c");
```

And it does so at compile-time.

2022-05-11 10:06 UTC, emilk commented
Very nice!

But I would suggest we simplify it. As far as I can recall I've never seen premultiplied alpha expressed in hex form. So I suggest we boil it down to a single macro that accepts both RGB and unmultiplied RGBA (`epaint::color_hex!("#55eedd") == epaint::color_hex!("#55eeddff")`).

For additive, users can just do `epaint::color_hex!("#ffeedd").additive()` (we can make `Color32::additive` `const fn`)

2022-05-11 19:05 UTC, newcomb-luke commented
Upon further testing, previously the from_rgb, from_rgb_additive, from_rgba_premultiplied were `const`, however from_rgba_unmultiplied due to the floating-point conversions that have to take place, is unable to be `const` [yet](https://github.com/rust-lang/rust/issues/57241). So only the conversion from the string literal to the array of values can be const. So the macro invocation itself cannot yet be `const`, but soon it could be. This isn't much slower than using the regular from_rgba_unmultiplied though.

2022-05-13 07:30 UTC, emilk requested changes
It's a bit of a shame that it is not `const` but yeah, not much to do about that right now. I think this looks good, but the macro needs a docstring!

2022-05-13 07:30 UTC, emilk commented on epaint/src/color.rs
> +#[macro_export]
```suggestion
/// Construct a [`Color32`] from a hex RGB or RGBA string.
///
/// ```
/// assert_eq!(hex_color!("#202122"), Color32::from_rgb(0x20, 0x21, 0x22));
/// assert_eq!(hex_color!("#abcdef12"), Color32::from_rgba_unmultiplied(0xab, 0xcd, 0xef, 0x12));
/// ```
#[macro_export]
```

2022-05-14 19:42 UTC, newcomb-luke commented on epaint/src/color.rs
> +#[macro_export]
Done!

2022-05-15 15:07 UTC, merged

2022-05-16 05:14 UTC, coderedart commented
is hex string assumed to be in linear space? or sRGB?
docs could mention that so its not confusing. 
`Color32` mention that `Internally this uses 0-255 gamma space sRGBA color with premultiplied alpha. Alpha channel is in linear space.`.