Text color map (Issue #173)
emilk/egui pull request #195
Opened 2021-02-27 16:03 UTC by the-drunk-coder

Please read the "Making a PR" section of [`CONTRIBUTING.md`](https://github.com/emilk/egui/blob/master/CONTRIBUTING.md) before opening a Pull Request!

2021-02-28 17:17 UTC, emilk requested changes
Thank you for this PR! Hot tip: configure your editor to run `cargo fmt` on save :)

2021-02-28 17:17 UTC, emilk commented on epaint/src/shape.rs
> +	color_map: TextColorMap,
No need to add a separate `MulticolorText` - just add `color_map: TextColorMap` to `Text`, and set it to `TextColorMap::default()` when there are no color changes

2021-02-28 17:17 UTC, emilk commented on epaint/src/tessellator.rs
> +    pub fn tessellate_multicolor_text(
I rather have just one `tesselate_text`. With `TextColorMap::default()` they should act the same anyway.

2021-02-28 17:17 UTC, emilk commented
I'll convert this to a draft and you can change it to "Ready for review" when it is green

2021-02-28 20:04 UTC, the-drunk-coder commented
I removed the additional `tesselate_multicolor_text` etc. I only kept the multicolor galley because there were already some methods in place, so I thought that was in line ...

2021-03-06 10:05 UTC, emilk requested changes
This is starting to look good!

What I think is missing is some way to use the color map, and a demonstration of it in the demo app. I think at least `Label`, and maybe `TextEdit`, should have an option to set a `TextColorMap`. It would be great to demonstrate it with some simple demo, at least for `Label`. It can be added to `egui_demo_lib/src/apps/demo/demo_window.rs`.

...or if you are feeling very ambitious, check out the syntax highlighting in `egui_demo_lib/src/apps/http_app.rs` which currently uses a bunch of labels, but could be just a single `Label` with a `TextColorMap`. To test that use `cargo run --all-features -p egui_demo_app` (you need to rebase on `master` first). Totally optional though!

2021-03-06 10:10 UTC, emilk commented
Oh, and please add a line to `CHANGELOG.md`!

Sorry for the slow review btw

2021-03-13 20:21 UTC, the-drunk-coder commented
No worries, got plenty of things on my plate as well. 

So, would you prefer having separate methods for the galleys in `Painter` ? Like, `galley_with_italics` and `galley_with_italics_multicolor` ? Or rather just one ? There's plenty of galley methods, so I'm not quite sure here ... personally I'd make separate ones ...

2021-03-13 20:30 UTC, the-drunk-coder commented
Also, now that I think about it, at least for `TextEdit`, I'm not sure whether it makes sense to set a static color map ? I mean, the way I use it it's generated dynamically based on the content.

2021-04-29 17:55 UTC, emilk reviewed
This needs a demo!

For instance, if `Label` was given a method to set a color map, then `egui_demo_lib/src/apps/http_app.rs` could be configured to use it for syntax highlighting (requires `syntect` feature) in `ColoredText::ui`.

2021-04-29 17:55 UTC, emilk commented on epaint/src/text/fonts.rs
> +                    "ComicMono".to_owned(),
please revert!

2021-04-29 17:55 UTC, emilk commented on egui/src/painter.rs
> +use epaint::{
Configure your editor to trim trailing spaces!

2021-08-29 19:18 UTC, emilk commented
Closed in favor of https://github.com/emilk/egui/pull/682 which is a complete rewrite of the text layout engine which supports color ranges and much, much more.

2021-08-29 19:18 UTC, closed without merging