Add custom_shader_version on glow renderer
emilk/egui pull request #1993
Opened 2022-09-01 13:29 UTC by ar37-rs

* Fix black screen by changing custom_shader_version to OpenGL ES 2.0 shader (ES100) on VirtualBox VMSVGA driver with OpenGL ES 2.0 and OpenGL 2.1 with no srgb support.
* More easier cross compiling for different targets.

2022-09-05 09:48 UTC, emilk requested changes
Looks good, but I think `custom_shader_version` is better named as just `shader_version`.

2022-09-05 09:48 UTC, emilk commented on crates/eframe/CHANGELOG.md
> +* Added `custom_shader_version` to `NativeOptions` for cross compilling support on different target OpenGL | ES versions (on native `glow` renderer only).
```suggestion
* Added `custom_shader_version` to `NativeOptions` for cross compilling support on different target OpenGL | ES versions (on native `glow` renderer only) ([#1993](https://github.com/emilk/egui/pull/1993))..
```

2022-09-05 09:48 UTC, emilk commented on crates/egui_glow/CHANGELOG.md
> +* small BREAKING change: Added `custom_shader_version` variable on `EguiGlow::new` for easier cross compilling on different OpenGL | ES targets.
```suggestion
* Added `custom_shader_version` variable on `EguiGlow::new` for easier cross compilling on different OpenGL | ES targets ([#1993](https://github.com/emilk/egui/pull/1993)).
```

2022-09-05 09:48 UTC, emilk commented on crates/egui_glow/src/winit.rs
> +    /// for automatic shader version detection set `custom_shader_version` to None
```suggestion
    /// For automatic shader version detection set `custom_shader_version` to `None`.
```

2022-09-05 09:48 UTC, emilk commented on crates/egui_glow/src/painter.rs
> +        };
```suggestion
        let shader_version = custom_shader_version.uwrap_or_else(|| ShaderVersion::get(&gl));
```

2022-09-05 09:48 UTC, emilk commented on crates/eframe/src/epi.rs
> +    /// the OpenGL ES 2.0 shader: ShaderVersion::Es100 can be used to solve blank texture problem (fallback shader).
```suggestion
    /// For OpenGL ES 2.0: set this to [`ShaderVersion::Es100`] to solve blank texture problem (by using the "fallback shader").
```

2022-09-05 09:48 UTC, emilk commented on crates/eframe/src/epi.rs
> +    /// cross compiling for VirtualBox VMSVGA driver with OpenGL 2.1 but doesn't support SRGB texture.
```suggestion
    /// Needed fo cross compiling for VirtualBox VMSVGA driver with OpenGL 2.1 which doesn't support SRGB texture.
    /// See <https://github.com/emilk/egui/pull/1993>.
```

2022-09-06 05:44 UTC, ar37-rs commented
> Looks good, but I think `custom_shader_version` is better named as just `shader_version`.

@emilk thank you, done changed,

2022-09-06 08:08 UTC, merged