eframe support for wgpu on the web
emilk/egui pull request #2107
Opened 2022-10-04 14:55 UTC by Wumpf

Adds a wgpu painter for eframe's web compilation (i.e. targeting wasm).
You can render the demo with it by replacing `glow` with `wgpu` in the feature list in `build_demo_web.sh`. Worked fine for me on manual testing!

Fixes #1755

Remaining things to figure out (after this PR):

* target is currently srgb, this causes blending to be done incorrectly. It seems wgpu doesn't support anything else for webgl canvases right now (why?)
* expose MSAA settings
* expose limits settings etc.
* allow targeting WebGPU

2022-10-04 15:49 UTC, Wumpf commented
filed wgpu issue for srgb issue https://github.com/gfx-rs/wgpu/issues/3058

2022-10-04 20:24 UTC, emilk commented
`cargo check -p egui_demo_app --lib --target wasm32-unknown-unknown` fails with:

```
error[E0597]: `*arg0` does not live long enough
  --> crates/egui_demo_app/src/lib.rs:83:1
   |
83 | #[wasm_bindgen]
   | ^^^^^^^^^^^^^^-
   | |             |
   | |             `*arg0` dropped here while still borrowed
   | borrowed value does not live long enough
   | argument requires that `*arg0` is borrowed for `'static`
   |
   = note: this error originates in the attribute macro `wasm_bindgen` (in Nightly builds, run with -Z macro-backtrace for more info)
```

some shenanigans with how `async` interacts with the `#[wasm_bindgen]` macro

2022-10-04 20:33 UTC, emilk commented
`crates/egui_demo_app/src/apps/custom3d_glow.rs` should be made to work before we merge this

2022-10-05 10:56 UTC, Wumpf commented
Fixed!
<img width="979" alt="image" src="https://user-images.githubusercontent.com/1220815/194044765-d1adf15b-78c0-42aa-aee1-812f0d7f10f7.png">

2022-10-05 12:32 UTC, emilk commented on crates/egui_demo_app/src/apps/custom3d_wgpu_shader.wgsl
> +};
this looks unused? O.o

2022-10-05 12:34 UTC, emilk requested changes

2022-10-05 13:04 UTC, Wumpf commented on crates/egui_demo_app/src/apps/custom3d_wgpu_shader.wgsl
> +};
oops! Fixed.
wgpu panics for errors and logs everying via logging crate; enabled pushing that to console locally and looked at standalone naga compilation via naga (via https://github.com/PolyMeilex/vscode-wgsl): It seems this isn't a warning right now and I also couldn't find anything normative in the spec on a quick glimpse. Going to ask on Naga Matrix chat.

2022-10-05 14:49 UTC, emilk commented
I get this warning in Firefox:

```
WebGL warning: getSyncParameter: ClientWaitSync must return TIMEOUT_EXPIRED until control has returned to the user agent's main loop. (only warns once)
```

No such warning on chromium.

2022-10-05 14:50 UTC, emilk commented
This works great, good job! ⭐

2022-10-05 14:50 UTC, emilk approved these changes

2022-10-05 15:58 UTC, Wumpf commented
> I get this warning in Firefox:
> 
> ```
> WebGL warning: getSyncParameter: ClientWaitSync must return TIMEOUT_EXPIRED until control has returned to the user agent's main loop. (only warns once)
> ```
> 
> No such warning on chromium.

Filed an issue https://github.com/gfx-rs/wgpu/issues/3064

2022-10-05 18:14 UTC, merged