Add ability to control double click reset in plot widget
emilk/egui pull request #2115
Opened 2022-10-06 11:33 UTC by Raymi306

While building a tool that uses the plot widget, I wanted to be able to disable the double click reset.
This PR allows for that.

2022-10-06 11:36 UTC, Raymi306 reviewed
I did some small housekeeping and tried to organize the allow_ struct fields in a consistent way.
I added a new struct field allow_double_click_reset.
The important bit is on line 818 where I added to the if guard using the new struct field.

2022-10-10 07:44 UTC, emilk requested changes

2022-10-10 07:44 UTC, emilk commented on crates/egui/src/widgets/plot/mod.rs
> +    /// Whether to allow double clicking to reset the
```suggestion
    /// Whether to allow double clicking to reset the view.
    /// Default: `true`.
```

2022-10-10 07:44 UTC, emilk commented on crates/egui/src/widgets/plot/mod.rs
> +        if response.double_clicked_by(PointerButton::Primary) && allow_double_click_reset {
small optimization

```suggestion
        if allow_double_click_reset && response.double_clicked_by(PointerButton::Primary) {
```

2022-10-10 07:57 UTC, merged