Fix keypress event
emilk/egui pull request #2334
Opened 2022-11-22 15:43 UTC by palako

A key can be pressed or not pressed. This is the status of the key, not an event. The `InputState::keys_down` attribute contains a collection of any key being held down at any given frame.  `InputState::key_down(Key)` returns true if a key is being held down. So far so good.

A key being pressed or released is an event, i.e. the change from being pressed to not being pressed, or from not being pressed to being pressed. While` InputState::key_released(Key`) returns true correctly only when the key was released on a given frame,` InputState::key_pressed(Key)` doesn't behave that way, and instead returns true as long as the key is held down.

Besides not allowing this method to be used to detect the actual key press, another unintended consequence is that on the frame where the key is released, sometimes both events will be there, and thus both _key_pressed_ and _key_released_ will return true.

The example in the second commit of this PR helps seeing this. Before applying the patch to _InputState_, press and hold the letter A, then release. First you'll see that during the key being pressed, not only you get true from `key_down()` but also from `key_press()`. Also if you try to do this a few times, you will see that sometimes the message "pressed" is printed AFTER the message "released" (note there's no release messages in the following screenshot, they key is being held down)

![Screenshot 2022-11-22 at 15 20 13](https://user-images.githubusercontent.com/131890/203356454-d2ce0ca8-3411-45f6-9a34-b973a8a9512c.png)

The root of the problem is the difference in meaning between pressed/released events in egui/eframe and egui-winit. For egui-winit, keyboard events mean something different, as implemented on State::on_keyboard_input. Keys pressed are added as Event::Key with pressed true (and this applies while the key is held down).

The patch on the first commit is very simple, and it just removes from the raw input events the key press if this key was already in the set of keys pressed from the previous frame. It of course leaves the keys_pressed set unaltered, so that the key can still be queried for being held down (there are only "held" messages in between a "pressed" and a "released" message in the following screenshot)

![Screenshot 2022-11-22 at 15 13 43](https://user-images.githubusercontent.com/131890/203357161-d34cdc43-7121-4046-8412-795c6502578a.png)

The API to the user doesn't change, but with this fix key_down and key_pressed will differ in behaviour. If someone was using key_pressed to detect if a key was being held down, this will stop working. They change is trivial though, just change the API call, the parameters are all the same.

2022-11-29 14:20 UTC, emilk requested changes
I tried to push an improvement to this PR but failed - perhaps you can `git cherrypick` it? 

https://github.com/emilk/egui/commit/a646c1259d8fcced4a281f42ca5de5ecfe0e56d1

2022-11-29 14:20 UTC, emilk commented on crates/egui/src/input_state.rs
> +                    //return false (thus filtering out the Event) if the key already existed in the set of pressed keys
rm dead code / confusing comment

2022-11-29 14:20 UTC, emilk commented on crates/egui/src/input_state.rs
> +                    //return false (thus filtering out the Event) if the key already existed in the set of pressed keys
Maybe
```suggestion
                    // We only retain presses that are novel (i.e. the first Press event, not those generated by key-repeat)
```

2022-11-30 14:18 UTC, palako commented
I've pushed a commit with all the requested improvements. 
Not sure what the formatting problem was. When I tried to cargo format as you explain in the doc, I got cargo suggesting hundreds of format changes all over the place in files I was not touching, so I thought better to leave it alone. Let me know if you want me to adjust something.
Cheers!

2022-11-30 19:39 UTC, emilk commented on CHANGELOG.md
> +* Keyboard press events are only pressent at the frame when the key was pressed, consistent with how key releases work.
```suggestion
* Keyboard press events are only present at the frame when the key was pressed, consistent with how key releases work ([#2334](https://github.com/emilk/egui/pull/2334)).
```

2022-11-30 19:40 UTC, merged

2022-11-30 19:40 UTC, emilk commented
Thanks!