Fallback on GLX when EGL initialization fails
emilk/egui pull request #2541
Opened 2023-01-04 04:58 UTC by sphaerophoria

On my machine eframe fails to initialize after commit 8eb687cf04dd2b68dfe467d142db6b8759425e16

This seems to be a result of a bad EGL configuration. With EGL_LOG_LEVEL=debug

libEGL debug: EGL user error 0x3003 (EGL_BAD_ALLOC) in eglCreateWindowSurface: dri3_surface_create Error: Glutin(Error { raw_code: Some(12291), raw_os_message: None, kind: OutOfMemory })

This seems to happen because the GLX fallback only kicks in when the display fails to initialize. In my case the display initializes fine but we fail to create the window surface.

Implement a more aggressive fallback where we try to fully initialize the glutin window context with EGL then GLX separately.

Although there is not a satisfying root cause to why EGL fails to initialize here, I believe it is reasonable behaviour to do our best to initialize the app if possible.

Closes <https://github.com/emilk/egui/issues/THE_RELEVANT_ISSUE>.

2023-01-04 06:15 UTC, coderedart commented
there exists an issue for this at https://github.com/emilk/egui/issues/2457

can you see if https://github.com/emilk/egui/pull/2526 fixes your problem (repo/branch link in that issue)?

2023-01-04 08:43 UTC, sphaerophoria commented
#2526 fixes it, but only because of https://github.com/emilk/egui/pull/2526/commits/37d66630e3a905c47448a23cb8f2e412d91a7195

If I revert that commit I get the same behavior. Makes sense as my PR effectively does the same thing (GLX works, EGL does not)

2023-01-04 08:51 UTC, sphaerophoria commented
I'll also note that I'll also note that with the following diff to glutin I see the same behavior using their window example

```
diff --git a/glutin_examples/src/lib.rs b/glutin_examples/src/lib.rs
index b3e2581..27ad808 100644
--- a/glutin_examples/src/lib.rs
+++ b/glutin_examples/src/lib.rs
@@ -37,9 +37,9 @@ pub fn main() {
     // The template will match only the configurations supporting rendering to
     // windows.
     let template = ConfigTemplateBuilder::new().with_alpha_size(8);

-    let display_builder = DisplayBuilder::new().with_window_builder(window_builder);
+    let display_builder = DisplayBuilder::new().with_window_builder(window_builder).with_preference(glutin_winit::ApiPrefence::PreferEgl);

     let (mut window, gl_config) = display_builder
         .build(&event_loop, template, |configs| {
             // Find the config with the maximum number of samples, so our triangle will
```

Haven't worked through the glutin docs yet, but IMO it indicates that something is wrong pretty far down the stack. 

I'll also argue that switching the order from GLX -> EGL vs EGL -> GLX isn't as robust a solution as what I've provided here. If on some systems we get the reverse behavior we're just failing the other way. Maybe that doesn't matter and in practice no one will hit that, but it's worth considering.

2023-01-04 10:21 UTC, coderedart commented
> I'll also argue that switching the order from GLX -> EGL vs EGL -> GLX isn't as robust a solution as what I've provided here. If on some systems we get the reverse behavior we're just failing the other way. 

I agree. but it means we have to bring back platform gated code for egl/wgl/glx/cgl etc..

@kchibisov I wonder if this should be something glutin-winit should be dealing with behind the scenes.

2023-01-04 10:48 UTC, kchibisov commented
The suggestions how to improve that are welcomed, and be aware that previous glutin had exactly the same issue, but I don't remember how far it was initializing...

Be aware that glutin right now can't automate that, since everything has its own step and you may fail later on. For example on android you'll only fail once you `Resume`, which may happen long after you setup the context.

If you want an aggressive fallback to GLX like that you'd need to go back at the moment of query for such thing. And also do a EGL termination and unloading, which glutin doesn't have right now (and never had) before.


In general GLX works more often then EGL and the same applies to WGL, since both of them are `native` solutions existed on the platforms. On Wayland you'll have just EGL. That's for example what was before, glutin was simply always trying GLX first and for most users it was just working.

2023-01-04 11:19 UTC, coderedart commented
> Be aware that glutin right now can't automate that, since everything has its own step and you may fail later on. For example on android you'll only fail once you Resume, which may happen long after you setup the context.
> If you want an aggressive fallback to GLX like that you'd need to go back at the moment of query for such thing. And also do a EGL termination and unloading, which glutin doesn't have right now (and never had) before.

understood. I will just leave it as `FallbackEgl` for now.  @emilk can make the final decision if he feels the complexity of dealing with retries is worth it.

2023-01-23 08:58 UTC, emilk requested changes
Nice!

2023-01-23 08:58 UTC, emilk commented on crates/eframe/src/lib.rs
> +    Custom(String),
```suggestion
    #[error("Failed to create glutin window context with all APIs")]
    GlutinWindow,
```

2023-01-23 08:58 UTC, emilk commented on crates/eframe/src/native/run.rs
> +                        tracing::error!("Failed to initialize option {}: {:?}", idx, e);
```suggestion
                        tracing::warn!("Failed to initialize option {}: {:?}", idx, e);
```

2023-01-28 23:16 UTC, sphaerophoria commented
Feedback applied, thanks!

2023-02-04 15:04 UTC, emilk commented
This needs `cargo fmt`

2023-02-08 08:46 UTC, closed without merging