Implement toggle for `egui::Window` to only accept move events from the title bar.
emilk/egui pull request #2775
Opened 2023-03-02 20:39 UTC by NotAPenguin0

Closes #2774. For a more detailed description of the problem, refer to that issue.

[demo gif](https://gifyu.com/image/S7ukY).

List of changes
- Added `egui::Window::movable_from_contents()` to toggle the new behaviour on.
- In `window::window_interaction()`, split resize and move behaviour, since they might now use two different rects.

My apologies that there are so many commits, it's the unfortunate result of some dependencies I have to manage while developing. Just squashing on merge should get rid of the problem.

2023-03-29 13:36 UTC, emilk requested changes

2023-03-29 13:36 UTC, emilk commented on crates/egui/src/containers/window.rs
> +    pub fn movable_from_contents(mut self, movable: bool) -> Self {
```suggestion
    /// Allow moving the window by dragging its content?
    ///
    /// Default: `true`.
    /// Regardless of this value, dragging the title-bar will move the window (if moveable).
    pub fn movable_from_contents(mut self, movable: bool) -> Self {
```

2023-03-29 13:36 UTC, emilk commented on crates/egui/src/containers/window.rs
> +        self.move_title_bar_only = !movable;
avoid negation in names

```suggestion
        self.movable_from_contents = movable;
```

2023-03-29 13:40 UTC, emilk requested changes
This seems like a lot of new code and complexity for a small change.

We should be able to just pipe in a smaller rect into `move_and_resize_window`?

2023-04-19 21:40 UTC, NotAPenguin0 commented
That is what I did initially, the problem is that this also moves the resize handle to a very weird and awkward position. I've also been able to implement this exact behaviour without touching egui internals at all, by simply doing
```rs
let (response, painter) = ui.allocate_painter(remaining_size, Sense::drag());
```
and handling the `drag` value from this `Response` myself, so I don't think this change is needed anymore

2026-09-09 12:46 UTC, emilk commented
Closing: this landed in #8183 as `Window::drag(WindowDrag::TitleBar)`. Thanks for the PR!

2026-09-09 12:46 UTC, closed without merging