Handle composition events to show suggestion on web
emilk/egui pull request #278
Opened 2021-04-07 14:59 UTC by n2

Handle composition events to show IME suggestion on web, as described in #248. Sorry for being late, I have been busy in the past few days.

2021-04-07 18:02 UTC, emilk requested changes
Thank you!

2021-04-07 18:02 UTC, emilk commented on egui_web/src/lib.rs
> +            // let event_type = event.type_();
```suggestion
```

2021-04-07 18:02 UTC, emilk commented on egui_web/src/lib.rs
>                  _s => panic!("Unknown type"),
```suggestion
                _s => {
                    console_err(format!("Unknown composition event type: {:?}", event.type_().as_ref());
                    None
                }
```

2021-04-09 08:27 UTC, n2 commented on egui/src/widgets/text_edit.rs
> +                            && state.has_candidate
Yes, has_candidate is introduced exactly for that purpose. On my test platforms(Windows 10, Ubuntu 18.04, MacOs Big Sur and iOS 14.4), when user click other place of canvas, compositionend message is send, and such reset logit is done in compositionend.

2021-04-12 18:57 UTC, emilk approved these changes
Thanks 🙏

2021-04-12 18:57 UTC, merged