use RawDisplayHandle for smithay clipboard init
emilk/egui pull request #2914
Opened 2023-04-17 21:09 UTC by lunixbochs

I believe this addresses #2912

2023-04-18 04:55 UTC, Mingun commented on crates/egui-winit/src/clipboard.rs
> +    pub fn new(_display_target: impl HasRawDisplayHandle) -> Self {
Doc comment should be updated to refer to the new parameter name

2023-04-18 04:55 UTC, Mingun commented on crates/egui-winit/src/lib.rs
> +    pub fn new(display_target: impl HasRawDisplayHandle) -> Self {
And here

2023-04-18 20:05 UTC, emilk requested changes
Looks good, but need `cargo clippy`

2023-04-18 20:05 UTC, emilk commented on crates/egui-winit/src/clipboard.rs
> +    pub fn new(_display_target: impl HasRawDisplayHandle) -> Self {
could use `&dyn HasRawDisplayHandle` here and elsewhere to avoid monomorphization

2023-04-18 20:05 UTC, emilk commented on crates/egui-winit/Cargo.toml
> +raw-window-handle = "0.5.0"
Move under the native dependency list below (`[target.'cfg(not(target_arch="wasm32"))'.dependencies]`)

2023-04-18 21:52 UTC, lunixbochs commented
addressed the inline comments

2023-04-19 06:54 UTC, emilk commented
tip: configure your editor to run `cargo fmt` on save

2023-04-19 06:55 UTC, emilk approved these changes

2023-04-19 07:14 UTC, merged

2023-04-19 07:14 UTC, emilk commented
thanks!