implement mint conversions
emilk/egui pull request #352
Opened 2021-05-06 15:41 UTC by LU15W1R7H

Implement conversions for [mint](https://docs.rs/mint) (math interoperability standard types).

- `impl {From, Into}<mint::Point2> for Pos2`
- `impl {From, Into}<mint::Vector2> for Vec2`

Closes #314

2021-05-06 19:56 UTC, emilk requested changes
Cool!

So an `egui` user would need to add `emath = { version = 0.11, features = ["mint"] }` to turn this on, correct? Would it maybe make sense to add `mint` as a feature in `egui` too, so that users could just change `egui = "0.11"` into `egui = { version = "0.11", features = ["mint"] }` without having to know about `emath`?

2021-05-06 19:56 UTC, emilk commented on emath/src/pos2.rs
> +// Compatibility and convenience conversions to and from (f32, f32):
rm misleading comment 

```suggestion
```

2021-05-06 19:56 UTC, emilk commented on emath/src/vec2.rs
> +// Compatibility and convenience conversions to and from (f32, f32):
rm misleading comment 

```suggestion
```

2021-05-06 20:02 UTC, LU15W1R7H commented on emath/src/pos2.rs
> +// Compatibility and convenience conversions to and from (f32, f32):
Sorry, forgot to adjust the comment 😅

2021-05-07 14:16 UTC, LU15W1R7H commented
I fixed the clippy issue.

2021-05-08 06:16 UTC, emilk approved these changes
Thanks!

2021-05-08 06:17 UTC, merged