Scroll Area: Prevent drag interaction outside the area
emilk/egui pull request #4611
Opened 2024-06-05 09:39 UTC by s-nie

* Closes https://github.com/emilk/egui/issues/4349

2024-06-05 09:59 UTC, emilk requested changes
I tested it, and it creates a bunch of bugs.

Try clicking around on the right side panel in the egui demo app, for instance.

I think the problem is that the late `interact` call means the interaction is _on top_ of the contents, while it should be _below_. So my idea wasn't great.

Better to store the final size for the next frame afterall

2024-06-05 11:47 UTC, s-nie commented
>I think the problem is that the late interact call means the interaction is on top of the contents, while it should be below. 

Right, I had not considered this. I changed the approach in https://github.com/emilk/egui/pull/4611/commits/4e1ea29c97ecfd7bdc026fdacecac8f2324b6679, the demo app works fine for me.

2024-06-06 13:36 UTC, emilk approved these changes

2024-06-06 13:36 UTC, merged

2024-06-06 13:36 UTC, emilk commented
Thanks!