Add `PopupCloseBehavior`
emilk/egui pull request #4636
Opened 2024-06-07 12:58 UTC by Umatriz

This PR adds `PopupCloseBehavior` to improve state of the <https://github.com/emilk/egui/issues/4607>

`PopupCloseBehavior` determines when popup will be closed.
- `CloseOnClick` popup will be closed if the click happens anywhere even in the popup's body
- `CloseOnClickAway` popup will be closed if the click happens somewhere else but in the popup's body.

It also adds a test in the demo app which contains several popups examples.

---

My ideas about <https://github.com/emilk/egui/issues/4607> is to make every tooltip and popup a menu. So it will provide more control over popups and tooltips (you will be able to close a popup by calling something similar to the `ui.close_menu` if you need to). You won't need to manually handle it's opening. And also will allow to have multiple popups opened. That means you can have a popup inside a popup. And it will also lead to the easier creation of the popups. (should we create a tracking issue to track changes because to me it seems like a huge amount of changes to be done?)

---

- Improvements on <https://github.com/emilk/egui/issues/4607>

2024-06-18 20:35 UTC, emilk requested changes
Good idea!

2024-06-18 20:35 UTC, emilk commented on crates/egui/src/containers/popup.rs
> +    /// It is used in the [`ComboBox`]
```suggestion
    /// Popup will be closed on click anywhere, inside or outside the popup.
    ///
    /// It is used in [`ComboBox`].
```

2024-06-18 20:35 UTC, emilk commented on crates/egui/src/containers/popup.rs
> +pub enum PopupCloseBehavior {
For completeness, I suggest we also add a third alternative called e.g. `IgnoreClicks` which ignores any clicks. You can only close it by pressing Escape or calling `Memory::close_popup` (and maybe later with `Ui::close_menu`).

----

Alternatively we replace this `enum PopupCloseBehavior` with 

```rs
struct PopupOptions {
    pub close_on_click_inside: bool,
    pub close_on_click_outside: bool,
    pub close_on_escape: bool,
}

impl PopupOptions {
    pub const CLOSE_ON_CLICK_ANYWHERE: Self = …;
    pub const CLOSE_ON_CLICK_INSIDE: Self = …;
}
```

That makes it much easier to expand with more options in the future

2024-06-18 20:35 UTC, emilk commented on crates/egui/src/containers/popup.rs
> +    CloseOnClickAway,
```suggestion
    CloseOnClickOutside,
```

2024-06-18 20:35 UTC, emilk commented on crates/egui/src/containers/popup.rs
> +        let is_close = match close_behavior {
```suggestion
        let should_close = match close_behavior {
```

("is close" sounds like it is about proximity)

2024-06-26 06:56 UTC, emilk approved these changes

2024-06-26 14:35 UTC, emilk commented
CI is red though

2024-06-27 06:00 UTC, Umatriz commented
@emilk I fixed the doc test so now everything should be fine

2024-06-27 07:42 UTC, merged