Introduce type parameter for plot points
emilk/egui pull request #4719
Opened 2024-06-27 14:16 UTC by FabianLippold

In order to supply custom data to plot points for use mainly in the label_formatter this introduces a new field which stores userdata.

Hovering over a plot point | Hovering over anything else
-|-
![image](https://github.com/emilk/egui/assets/174022351/55511bd4-8e28-439c-a66e-164b78371da9)|![image](https://github.com/emilk/egui/assets/174022351/8075ce29-b365-4bae-bd34-0375738efe9b)

Of course this requires PlotPoint to have a generic type parameter which then requires lots of other structs to be generic too.

The userdata field is optional, since a PlotPoint can be a Point supplied by the user when constructing a plot item, but it can also be generated by the library.

Since this requires quite big changes this is a draft pr for now.

2024-06-27 14:27 UTC, Mingun commented
At least, you can make generic parameters optional (`<T = ()>`)

2024-06-28 08:05 UTC, FabianLippold commented
Yes thats a good Idea, but the defaults only seem to apply when you use \<T> and not T itself.

See https://github.com/rust-lang/rust/issues/36980.

![image](https://github.com/emilk/egui/assets/174022351/e35351ad-990a-49e3-be31-586bebf57f69)
![image](https://github.com/emilk/egui/assets/174022351/5b2001ed-ea21-4875-b01d-296245fa099c)

2024-06-28 10:30 UTC, emilk requested changes
I'm not a big fan of adding templates to everything. It not only makes the core more complex, it also means monomorphization will duplicate the code in the binary, ballooning e.g. the .wasm size.

If you want to attach user-data to points, I suggest you report `Points::id` together with the point index (usize) to the user. The user can then look up the data they need with a hashmap or similar.

2024-07-03 10:31 UTC, FabianLippold commented
@emilk I tried it and it works with only a few modifications to the library.
But it is quite cumbersome to use, since you need an Arc<Mutex<...>> for the label_formatter and the plot_ui to be able to use the same HashMap. This also requires you to create or re-fill a HashMap on every draw...

Is this what you had in mind or is there a simpler way to do this?

2024-07-15 16:58 UTC, emilk commented
`egui_plot` has recently been moved to its own repository, at https://github.com/emilk/egui_plot

This will hopefully speed up its development by having more reviewers and maintainers.

Please re-open this PR at https://github.com/emilk/egui_plot/pulls

2024-07-15 16:58 UTC, closed without merging