Add a menu button with text and image
emilk/egui pull request #4748
Opened 2024-07-01 13:39 UTC by NicolasBircksZR

In order to make it possible that all buttons can have the same style with a text and an image I created a `menu_text_image_button`.

It works the same way as all the other menu buttons.

2024-07-01 17:51 UTC, emilk commented on crates/egui/src/ui.rs
> +            menu::submenu_button(self, menu_state, String::new(), add_contents)
you should pass in the title here instead of `String::new`

2024-07-02 07:20 UTC, emilk commented on crates/egui/src/menu.rs
> +    image_button: Button<'_>,
```suggestion
/// Build a top level menu with an text and button.
///
/// Responds to primary clicks.
fn stationary_menu_text_image_impl<'c, R>(
    ui: &mut Ui,
    button: Button<'_>,
```

2024-07-02 07:20 UTC, emilk commented on crates/egui/src/menu.rs
> +fn stationary_menu_text_image_impl<'c, R>(
I'm not sure we need `stationary_menu_image_impl` anymore. A normal `Button` supports both text and image, so the `ImageButton` versions of these functions shouldn't be needed anymore

2024-07-09 06:17 UTC, emilk commented on crates/egui/src/ui.rs
> +        image: impl Into<Image<'a>>,
Let's put them in the same order as they will appear (image left of button)

```suggestion
    pub fn menu_image_text_button<'a, R>(
        &mut self,
        image: impl Into<Image<'a>>,
        title: impl Into<WidgetText>,
```

2024-07-09 06:19 UTC, NicolasBircksZR commented
@emilk Updated it - does this work now as you wanted?

2024-07-09 07:05 UTC, emilk requested changes

2024-07-09 07:05 UTC, emilk commented on crates/egui/src/ui.rs
> +    /// ```
This doctest is now outdated. You can use `egui::__run_test_ui` to actually run your doctests; see for instance

https://github.com/bash/egui/blob/495d72397b55d152597736cf5deece23fb5f342d/crates/egui/src/ui.rs#L19-L30

2024-07-09 07:05 UTC, emilk commented on crates/egui/src/menu.rs
> -pub fn menu_image_button<R>(
Let's keep the old `menu_image_button` as well, but `#[deprecated]`, and forward it to `menu_custom_button`, so we don't break users code.

You may need to make `ImageButton::image` `pub(crate)` in order to turn it into a `Button`.

2024-07-09 09:56 UTC, emilk approved these changes

2024-07-09 14:51 UTC, merged

2024-07-09 14:51 UTC, emilk commented
Thanks!