Function to specify `Align` to `Lable`
emilk/egui pull request #4975
Opened 2024-08-17 17:36 UTC by rustbasic

Function to specify `Align` to `Lable`

There are cases where you want to display `Label` on the left or right regardless of other `Layout` specifications.

Before : Note the part showing the rust source code.
![20240818-1](https://github.com/user-attachments/assets/a08f7594-1ec1-4c6a-b96d-1a5f735d02c1)

After : Note the part showing the rust source code.
![20240818-2](https://github.com/user-attachments/assets/807ff9cf-f8cd-4415-9c78-b62869d1696d)

2024-08-18 11:01 UTC, bircni commented
maybe change the function name to text_align as this only aligns the text inside the label not the label itself

2024-08-18 11:33 UTC, rustbasic commented
> maybe change the function name to text_align as this only aligns the text inside the label not the label itself

Yes, that would be great too. Let's wait for emilk's review.

2024-08-26 07:52 UTC, emilk requested changes

2024-08-26 07:52 UTC, emilk commented on crates/egui/src/widgets/label.rs
> +    /// Set [`Self::align`] to [`Align`].
This doesn't explain anything

2024-08-26 07:52 UTC, emilk commented on crates/egui/src/widgets/label.rs
> +        self.align = Some(align);
`halign` is probably a better name

2024-08-26 13:31 UTC, emilk commented on crates/egui/src/widgets/label.rs
> +    /// Set [`Self::halign`] to [`Align`].
```suggestion
```

2024-08-26 13:38 UTC, merged