Add max click timings & distance to `Options`
emilk/egui pull request #4986
Opened 2024-08-19 16:23 UTC by Azorlogh

* [x] I have followed the instructions in the PR template

Moves the click timing & distance constants to the Options struct so they can be configured by users.

Note: This need came up as part of my investigation of https://github.com/mvlabat/bevy_egui/issues/302. Essentially, on some platforms we are not guaranteed to have correct timekeeping so it's useful to be able to disable the max click duration in this case.

2024-08-19 16:25 UTC, Azorlogh commented on crates/egui/src/context.rs
> +                &self.memory.options,
This isn't super pretty, but otherwise it conflicts with the mut access of `memory` above

2024-08-26 07:51 UTC, emilk requested changes
Makes sense, but we need to fix that deadlock

2024-08-26 07:51 UTC, emilk commented on crates/egui/src/ui.rs
> +    let is_clicking = ui.memory(|m| ui.input(|i| i.pointer.could_any_button_be_click(&m.options)));
This deadlocks (try holding down all modifier keys in the demo app)

2024-08-26 09:33 UTC, Azorlogh commented
> There is an alternative PR for this in #4942 which I think uses a slightly better approach, and avoids the deadlock

Oh I totally missed it! Yeah I agree that other one is a lot cleaner :ok_hand: I'll close this one

2024-08-26 09:33 UTC, closed without merging