Fix : Submenus are inaccessible via keyboard Enter/Space (Response::fake_primary_click)
emilk/egui pull request #5230
Opened 2024-10-07 22:07 UTC by abdul2801

Fixes Submenus are inaccessible via keyboard Enter/Space

* [`crates/egui/src/menu.rs`](diffhunk://#diff-caeae5d2b2528dd614ea0f8330f200c10dbedb8152f9dacb55dffd71d94d10abL701-R701): Enhanced the submenu opening condition to include pointer hovering over the current submenu and button clicks.

* Closes <https://github.com/emilk/egui/issues/5221>

2024-12-12 10:41 UTC, emilk approved these changes

2024-12-12 10:41 UTC, emilk commented on .vscode/settings.json
> +    "workbench.colorTheme": "CodeSandbox Black",
```suggestion
```

2024-12-12 10:43 UTC, emilk requested changes
You broke something:
![bad-menu](https://github.com/user-attachments/assets/0324adbc-6ac0-437a-857b-98422797bc8f)

2024-12-12 12:06 UTC, abdul2801 commented
looks like the hovering_current_submenu() check was causing the issue.Just checking for clicked() works fine

2025-01-23 14:03 UTC, abdul2801 commented
> still broken, but in a new way

Hmm , Is it the fact that the other menu(nested 1) wont open while nested is being hover with Enter Key

![media-2025-01-23_19 29 52  MConverter eu](https://github.com/user-attachments/assets/eceeab86-d245-4a1b-9f1e-6dcf737bee4e)

2025-03-13 14:14 UTC, lucasmerlin commented
I'll close this since we now have a new menu implementation (See #5716)

2025-03-13 14:14 UTC, closed without merging