Make ImageLoader use background thread
emilk/egui pull request #5394
Opened 2024-11-20 20:55 UTC by bircni

This is the same change as in #4069 but as this is stale I wanted to reopen a non stale PR

Modifies ImageLoader's load function to use background threads for the image decoding work. This avoids blocking the main thread that is especially noticeable when loading many images at once.

This was modelled after the other loader implementations that also use threads.

* Closes <https://github.com/emilk/egui/issues/5375>
* [ ] I have followed the instructions in the PR template

2024-11-20 21:36 UTC, bircni commented
I know the workaround for wasm is not the best so if you have any ideas - feel free to tell me

2025-01-13 03:37 UTC, zezic commented
Can we do the same for the `SvgLoader` parsing & rasterization step? I mean, to make the inner `load_svg_bytes_with_size(...)` call non-blocking. I have to re-rasterize a giant SVG and it makes whole UI block when `egui::Image` is getting showed after another call to `Context::forget_image` 😔

2025-03-05 10:44 UTC, lucasmerlin requested changes
Awesome, gave this a try in [hello_egui's gallery example](https://lucasmerlin.github.io/hello_egui/#/example/gallery) which is stuttery slow when running it locally in dev mode, and with these changes it's buttery smooth. 

Please fix the deadlock though 🙏

2025-03-05 10:44 UTC, lucasmerlin commented on crates/egui_extras/src/loaders/image_loader.rs
> +            match entry {
This immediately deadlocks for me (when e.g. starting egui demo app).

With the following changes it works fine though:


```suggestion
        }

        let entry = self.cache.lock().get(uri).cloned();
        if let Some(entry) = entry {
            match entry {
```
(And removing the `let cache = self.cache.lock();` in line 61)

2025-03-05 17:45 UTC, bircni commented on crates/egui_extras/src/loaders/image_loader.rs
> +        let cache = self.cache.lock();
```suggestion
```

2025-03-15 23:41 UTC, lucasmerlin approved these changes

2025-03-15 23:41 UTC, lucasmerlin commented on crates/egui_extras/src/loaders/image_loader.rs
> +            drop(cache_lock);
```suggestion
            let uri = uri.to_owned();
            cache.lock().insert(uri.clone(), Poll::Pending);
```

2025-03-20 09:55 UTC, emilk approved these changes
Nice, thank you!

2025-03-20 09:58 UTC, emilk requested changes

2025-03-20 09:58 UTC, emilk commented on crates/egui_extras/src/loaders/image_loader.rs
> +            uri: &str,
```suggestion

		#[cfg(not(target_arch = "wasm32"))]
        fn load_image(
            _ctx: &egui::Context,
            uri: &str,
```

2025-03-20 09:58 UTC, emilk commented on crates/egui_extras/src/loaders/image_loader.rs
> +                        load_image(ctx, uri, &self.cache, bytes)
```suggestion
                    load_image(ctx, uri, &self.cache, bytes)
```

2025-03-20 09:59 UTC, bircni commented
@emilk fixed

2025-03-20 12:37 UTC, emilk commented
CI is red though

2025-03-20 22:02 UTC, bircni commented
@emilk not the most beautiful way but green

2025-03-21 12:43 UTC, emilk approved these changes
If you revert the snapshot images then the merge conflicts should dissappear

2025-03-21 12:43 UTC, emilk commented on crates/egui_demo_app/tests/snapshots/imageviewer.png
There should be no need to update any screeshots afaict?

2025-03-21 12:43 UTC, emilk commented on crates/egui_extras/src/loaders/image_loader.rs
> +                        assert!(matches!(prev, Some(Poll::Pending)));
```suggestion
                        debug_assert!(matches!(prev, Some(Poll::Pending)));
```

2025-03-21 12:43 UTC, emilk commented on crates/egui_extras/src/loaders/image_loader.rs
> +                        load_image(ctx, uri, &self.cache, &bytes)
just use the exact same file signature instead:

```suggestion
                        load_image(ctx, uri, &self.cache, bytes)
```

2025-03-21 16:46 UTC, bircni commented on crates/egui_demo_app/tests/snapshots/imageviewer.png
Please refer to @lucasmerlin

2025-03-25 09:17 UTC, merged

2025-03-25 09:17 UTC, emilk commented
Thanks!