Add screenshot support for eframe web
emilk/egui pull request #5438
Opened 2024-12-05 14:31 UTC by lucasmerlin

This implements web support for taking screenshots in an eframe app (and adds a nice demo).
It also updates the native screenshot implementation to work with the wgpu gl backend. 

The wgpu implementation is quite different than the native one because we can't block to wait for the screenshot result, so instead I use a channel to pass the result to a future frame asynchronously.  

* Closes <https://github.com/emilk/egui/issues/5425>
* [x] I have followed the instructions in the PR template

https://github.com/user-attachments/assets/67cad40b-0384-431d-96a3-075cc3cb98fb

2024-12-05 16:34 UTC, lucasmerlin commented
Put this back to draft because `surface.get_capabilities(&render_state.adapter).usages.contains(wgpu::TextureUsages::COPY_DST);` doesn't really work as expected, @Wumpf will open a wgpu issue about it.

I'll need to update this to render the texture to the surface via a triangle instead of using copy_texture_to_texture, so we can properly support all platforms. I'll also do this for the native implementation, since there screenshots also don't work with the wgpu gl backend.

2024-12-05 17:05 UTC, Wumpf commented
Related wgpu things:
* https://github.com/gfx-rs/wgpu/pull/6668
* https://github.com/gfx-rs/wgpu/issues/6667


... but really the problem is that `COPY_DST` surfaces is not portable and [potentially slow](https://github.com/gpuweb/gpuweb/issues/437)

2024-12-12 13:32 UTC, Wumpf requested changes
nice!
PR description is now outdated.
Comments are mostly nits about styling and efficiency (if anything the encoder one bugs me most actually) but what I'd like to insist on is refactoring/removing the blocking path - this code dupl doesn't really make sense and I don't think we should have a blocking path in the first place.

2024-12-12 14:08 UTC, lucasmerlin commented on crates/egui-wgpu/src/blit.wgsl
> +//-1,1           1,1
I copied it from the [wgpu examples](https://github.com/gfx-rs/wgpu/blob/28a3e97dde5322ffb6c23ae4cfa69d981ba51ac0/examples/src/mipmap/blit.wgsl#L7) haha

2024-12-12 16:36 UTC, lucasmerlin commented
@Wumpf I've implemented everything you asked for (except for the texture_format changes, as discussed)

2024-12-12 18:17 UTC, Wumpf approved these changes
thank you so much for addressing all those! 🚢

2024-12-12 18:17 UTC, merged