Serialize window maximized state in `WindowSettings`
emilk/egui pull request #5554
Opened 2024-12-31 20:57 UTC by landaire

A user of my Windows application reported a papercut where the application restores its size on next load, but does not restore its maximized state. This PR fixes that.

To test, I patched https://github.com/emilk/eframe_template to use my local code since I knew that template saves/restores window data. Testing methodology was to simply `cargo run`, maximize the application, then close the application. `cargo run` again and the application should start maximized.

* [ x ] I have followed the instructions in the PR template
* * This is mostly true, I had difficulties running `./scripts/check.sh` for some reason. Possibly a bad Python version?

2025-01-02 22:47 UTC, emilk approved these changes
code LGTM

2025-01-03 08:07 UTC, landaire commented
Just wanted to note I _think_ this fixes #1517.

2025-01-03 14:29 UTC, emilk requested changes
Unfortunately, this leads to a deadlock on Mac when running `cargo run -p custom_window_frame`


See also https://github.com/emilk/egui/pull/3612

2025-01-03 17:39 UTC, landaire commented
Will take a look to see if I can resolve the deadlock.

2025-01-03 19:41 UTC, landaire commented
Left a comment in #3494 and also created https://github.com/rust-windowing/winit/issues/4071.

For now I've removed the erroneous unconditional `maximized` logic in `update_viewport_info`. This retains the desired behavior of this diff, while preventing the logic from being invoked on macOS (tested with both `cargo run -p custom_window_frame` and my original testing steps)

2025-01-06 08:19 UTC, emilk commented
I can confirm that `custom_window_frame` no longer deadlocks on my Mac - thanks!

2025-01-06 08:19 UTC, merged