Add collapsing header select as selectable label
emilk/egui pull request #585
Opened 2021-07-26 23:53 UTC by gents83

I've added possibility to have collapsing header with same functionality of selectable label, without breaking previous functionalities.
This is useful to achieve hierarchies or folder dialog with selection.
Here you can find an example:

![egui_content_browser](https://user-images.githubusercontent.com/62186646/127073562-9023ab91-c1bd-4004-8f47-22c83a4e5d7c.gif)

> 
    fn populate_with_folders_tree(ui: &mut Ui, root: &Path, data: &mut FolderDialogData) {
        for_each_folder_in(root, |path| {
            let selected = data.selected_folder == path.to_path_buf();
            if is_folder_empty(path) {
                if ui
                    .selectable_label(selected, path.file_stem().unwrap().to_str().unwrap())
                    .clicked()
                {
                    data.selected_folder = path.to_path_buf();
                }
            } else {
                let collapsing = CollapsingHeader::new(path.file_stem().unwrap().to_str().unwrap())
                    .selectable(true)
                    .selected(selected);
                let header_response = collapsing
                    .show(ui, |ui| {
                        Self::populate_with_folders_tree(ui, path, data);
                    })
                    .header_response;
                if header_response.clicked() {
                    data.selected_folder = path.to_path_buf();
                }
            }
        });
    }

Closes <https://github.com/emilk/egui/issues/417>.

2021-08-05 16:42 UTC, gents83 commented
Here you can find an example of what we could obtain with Panels that could be used inside other ui elements.
Once integrated I would be glad to add an example inside demo too, if for you is ok @emilk :)


https://user-images.githubusercontent.com/62186646/128388159-c703e2fd-b120-45b1-8593-9536d290c3f8.mp4

2021-08-15 14:52 UTC, emilk requested changes
Selectable `CollapsingHeader` and UI panels are both great ideas, but they are very different. Please split them up into two PR:s and add some demo code for them so they can be tested!

2021-08-15 14:52 UTC, emilk commented on egui/src/containers/collapsing_header.rs
> +    pub fn selectable(mut self, selectable: bool) -> Self {
```suggestion
    /// Can the header be selected by clicking it? Default: `false`.
    pub fn selectable(mut self, selectable: bool) -> Self {
```

2021-08-16 08:59 UTC, gents83 commented
Created 2 separated pull requests and closing this one

2021-08-16 08:59 UTC, closed without merging