Plot interaction methods
emilk/egui pull request #766
Opened 2021-10-03 22:08 UTC by EmbersArc

Closes #734.

I went with option 2 described in #734. This is a small breaking change and updating shouldn't be difficult. In the long run we can use this to add even more methods for interacting with the plot.

Might be a bit rough around the edges so feel free to suggest improvements.

2021-11-01 19:07 UTC, emilk requested changes
Overall this looks great!

What do you think about using `Value` instead of `Pos2` for the values in plot-coordinates?

We could add helpers to `Value` (`to_pos2` and `to_vec2`) instead.

`Value` could also do with a better name, but that's another problem :)

2021-11-11 22:07 UTC, EmbersArc commented on egui/src/widgets/plot/mod.rs
> +pub struct PlotUi {
I added the comment except for the note that it should not be created directly, as that is not possible anyway.

2021-11-11 22:10 UTC, EmbersArc commented
I had completely missed your review and only just saw it. Sorry about the delay. I agree with all of your suggestions and have made the changes.

2021-11-12 23:48 UTC, EmbersArc commented
I tested this today and am pretty happy with how it works. I'd like to add the following features as well though:

* Access to `Ui` inside the closure as well. Either through the `plot_ui` struct or as a second argument.
* A `plot_to_screen` conversion, to enable custom drawing in screen coordinates based on items in the plot.
* A way to get the current plot bounds.

2021-11-13 10:55 UTC, emilk approved these changes
Excellent!

2021-11-13 10:56 UTC, merged