Fix nested scrolling.
emilk/egui pull request #83
Opened 2020-12-27 20:34 UTC by lucaspoffo

Fixes #59

Added the scroll_delta to the FrameState so we use this value instead of the actual scroll input, so when an inner ScrollArea is scrolling it will clear the value and the Parent can't use it. When no actual scroll is happening the value is not cleared and the parent scroll may use it.

2020-12-28 10:21 UTC, emilk requested changes
Very nice! I just have some minor nits

2020-12-28 10:21 UTC, emilk commented on egui/src/context.rs
> +    }
I'd prefer if `scroll_delta` was just made `pub(crate)` to make the use of it more transparent (and less code!).

2020-12-28 10:21 UTC, emilk commented on egui/src/containers/scroll_area.rs
> +            if scrolling_top || scrolling_bottom {
```suggestion
            let scrolling_up = state.offset.y > 0.0 && scroll_delta.y > 0.0;
            let scrolling_down = state.offset.y < max_offset && scroll_delta.y < 0.0;

            if scrolling_up || scrolling_down {
```

2020-12-28 19:35 UTC, lucaspoffo commented
:+1: Thanks for the suggestion, using pub(crate) is something that I always forget is a thing.

2020-12-29 11:00 UTC, emilk approved these changes
Works great - thanks!

2020-12-29 11:24 UTC, merged