implement vertical slider orientation
emilk/egui pull request #875
Opened 2021-11-04 07:26 UTC by B-Reif

2021-11-06 11:26 UTC, emilk commented
I've skimmed through it, and overall it looks good! Will review properly when I find the time.

2021-11-07 20:05 UTC, emilk requested changes

2021-11-07 20:05 UTC, emilk commented on egui/src/widgets/slider.rs
> +    pub fn new_vertical<Num: emath::Numeric>(
It seems unnecessary to have both this and the `.orientation` builder.

Perhaps `Slider::new(value, 0..100).vertical()` is a nicer way to construct a vertical slider anyway? And then we don't need `new_vertical`, `from_get_set_vertical` and `from_get_set_inner`

2021-11-07 20:05 UTC, emilk commented on egui/src/widgets/slider.rs
> +    pub fn orientation(mut self, orientation: SliderOrientation) -> Self {
```suggestion
    /// Vertical or horizontal slider? The default is horizontal.
    pub fn orientation(mut self, orientation: SliderOrientation) -> Self {
```

2021-11-07 20:05 UTC, emilk commented on egui/src/widgets/slider.rs
> +                (rect.top() + handle_radius)..=(rect.bottom() - handle_radius)
I think the default for a vertical slider should be higher values higher up, and lower values lower down:

```suggestion
                (rect.bottom() - handle_radius)..=(rect.top() + handle_radius)
```

2021-11-07 20:06 UTC, emilk commented
<img width="80" alt="Screen Shot 2021-11-07 at 21 05 12" src="https://user-images.githubusercontent.com/1148717/140660189-ec5e21c3-19b5-4752-8ae4-b690aa9776bb.png">

This looks a bit bad to me. I guess most people who use a vertical slider won't want the label text (no shown above), but the slider value would be very nice to show, and should be _below_ the vertical slider.

2021-11-09 00:52 UTC, B-Reif commented
Ok, made review changes and moved the value below the slider. Also added a new method `add_contents` to invoke inside of either `ui.horizontal` or `ui.vertical` respectively.

![image](https://user-images.githubusercontent.com/12357846/140841666-22d3d597-2161-4bf0-bdc2-97a9e0d29a9a.png)

This implementation will arrange the slider, value, and then label in a vertical layout. We could further group the value and label onto one horizontal line.

2021-11-09 00:57 UTC, B-Reif commented
I'm having some issues with the keyboard step functionality of Slider, but I experience them on the current master branch also. These could probably be resolved in a separate PR.

2021-11-13 11:02 UTC, emilk approved these changes

2021-11-13 11:03 UTC, merged